In [1]:
#Read the user input:
a=input()
print(a)

saurabh
saurabh

In [2]:
#Check the default data type of input from console is String:
name = input("Enter name: ")
age = input("Enter age: ")
print("Data type of name: ", type(name))
print("Data type of age: ", type(age))

Enter name: saurabh
Enter age: 18
Data type of name:  <class 'str'>
Data type of age:  <class 'str'>

In [3]:
#Implicit Type Conversion
x = 123
y = 1.23
z = x + y
print("Datatype of x:", type(x))
print("Datatype of y:", type(y))
print("Value of z:", z)
print("Datatype of z:",type(z))

Datatype of x: <class 'int'>
Datatype of y: <class 'float'>
Value of z: 124.23
Datatype of z: <class 'float'>

In [4]:
#Explicit Type Conversion:
#Print sum of two numbers taken from the user
num_1 = int(input("Enter first num: "))
num_2 = int(input("Enter second num: "))
print('Data Type of num_1:',type(num_1))
print('Data Type of num_2:',type(num_2))
result = num_1 + num_2
print("The sum of given numbers is : ", result)

Enter first num: 5
Enter second num: 6
Data Type of num_1: <class 'int'>
Data Type of num_2: <class 'int'>
The sum of given numbers is :  11

In [5]:
# Multiple input values in a single line
name, age, score = input("Enter student's name, age and score:").split()
print("Student Name:", name)
print("Student Age:", age)
print("Student Score:", score)

Enter student's name, age and score:saurabh 18 50
Student Name: saurabh
Student Age: 18
Student Score: 50